Special_Collections_And_University_Archives:
  name: 'Special Collections and University Archives'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  building: 'Green Library'
  address1: '557 Escondido Mall'
  address2: ''
  city: 'Stanford'
  state: 'CA'
  zip: '94305'
  country: 'USA'
  phone: '(650) 725-1022'
  contact_info: 'specialcollections@stanford.edu'
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/collection/image/Collections-Super-Enlight.jpg'
MyRepository:
  name: 'My Repository'
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam semper sagittis tellus, sit amet dapibus sapien tristique eu. Nam vitae porttitor lorem, vel commodo sem. Sed eu dictum risus, tristique porttitor diam. Pellentesque eget accumsan lacus. Aliquam a lectus ex. Proin interdum et augue at commodo. Suspendisse potenti. Curabitur gravida, nulla vitae sollicitudin molestie, metus augue luctus ligula, euismod fringilla erat enim ac ex. Cras a pretium massa, sit amet tempus turpis.'
  building: 'My Building'
  address1: 'My Street Address'
  address2: 'My Extra Address'
  city: 'My City'
  state: 'My State'
  zip: '12345'
  country: 'My Country'
  phone: '123-456-7890'
  contact_info: 'My Contact Info'
  thumbnail_url: 'http://example.com/thumbnail.jpg'
